Master dev
alexk2111/android-fundamentals pull request #1
Opened 2021-09-17 15:32 UTC by alexk2111

2021-09-18 17:00 UTC, ASKabanets requested changes
OK in general. Minor comments. Also, branch name and PR name should be more self-explained than `master-dev`

2021-09-18 17:00 UTC, ASKabanets commented on StartAndroid/app/src/main/java/com/sigmasoftwere/akucherenko/startandroid/MainActivity.kt
> +    private var mCount = 0
`mCount ` -> `count `
Same with others

2021-09-18 17:00 UTC, ASKabanets commented on StartAndroid/app/src/main/java/com/sigmasoftwere/akucherenko/startandroid/MainActivity.kt
> +    private val LOG_TAG = MainActivity::class.java.simpleName
Ok, but try to use https://github.com/JakeWharton/timber
It's kinda "industry standard"

2021-09-18 17:00 UTC, ASKabanets commented on StartAndroid/app/src/main/java/com/sigmasoftwere/akucherenko/startandroid/MainActivity.kt
> +        mShowCount = findViewById(R.id.tv_show_count)
Try to use https://medium.com/androiddevelopers/use-view-binding-to-replace-findviewbyid-c83942471fc instead `findViewById`

2021-09-18 17:00 UTC, ASKabanets commented on StartAndroid/app/src/main/java/com/sigmasoftwere/akucherenko/startandroid/MainActivity.kt
> +        Toast.makeText(this, R.string.toast_message, Toast.LENGTH_SHORT).show()
No reason to make single-line function for showing toast

2021-09-18 17:00 UTC, ASKabanets commented on StartAndroid/app/src/main/java/com/sigmasoftwere/akucherenko/startandroid/MainActivity.kt
> +        if (mCount > 0)
Add brackets

2021-09-18 17:00 UTC, ASKabanets commented on StartAndroid/app/src/main/res/layout-land/activity_main.xml
> +        android:id="@+id/tv_show_count"
`tv_show_count ` -> `showCountTextView`
Similar with others

2021-09-18 17:00 UTC, ASKabanets commented on StartAndroid/app/src/main/res/layout-land/activity_main.xml
> +        android:background="#FFFF00"
`#FFFF00` move to `colors.xml` resources

2021-09-18 17:00 UTC, ASKabanets commented on TwoActivities/app/src/main/java/com/sigmasoftwere/akucherenko/twoactivities/MainActivity.kt
> +    private lateinit var mMessageEditText: EditText
`mMessageEditText ` -> `messageEditText `

2021-09-18 17:00 UTC, ASKabanets commented on TwoActivities/app/src/main/java/com/sigmasoftwere/akucherenko/twoactivities/MainActivity.kt
> +class MainActivity : AppCompatActivity() {
Add empty line

2021-09-18 17:00 UTC, ASKabanets commented on TwoActivities/app/src/main/java/com/sigmasoftwere/akucherenko/twoactivities/MainActivity.kt
> +
Remove empty line

2021-09-18 17:00 UTC, ASKabanets commented on TwoActivities/app/src/main/java/com/sigmasoftwere/akucherenko/twoactivities/SecondActivity.kt
> +const val  EXTRA_REPLY = "com.sigmasoftwere.akucherenko.twoactivities.extra.REPLY"
Remove space

2021-09-18 17:00 UTC, ASKabanets commented on TwoActivities/app/src/main/java/com/sigmasoftwere/akucherenko/twoactivities/SecondActivity.kt
> +    private lateinit var mReply: EditText
Naming

2021-09-18 17:00 UTC, ASKabanets commented on TwoActivities/app/src/main/java/com/sigmasoftwere/akucherenko/twoactivities/SecondActivity.kt
> +    override fun onCreate(savedInstanceState: Bundle?) {
Add empty line

2021-09-18 17:00 UTC, ASKabanets commented on TwoActivities/app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/editText_main"
Id's naming

2021-09-18 17:00 UTC, ASKabanets commented on TwoActivities/app/src/main/res/layout/activity_second.xml
> +        android:id="@+id/text_header"
Id's naming

2021-09-18 17:00 UTC, ASKabanets commented on StartAndroid/.idea/.gitignore
> +# Default ignored files
Add `.idea` folder to `.gitignore`

2021-09-20 11:51 UTC, alexk2111 commented on StartAndroid/app/src/main/java/com/sigmasoftwere/akucherenko/startandroid/MainActivity.kt
> +    private var mCount = 0
Variable renamed

2021-09-20 11:52 UTC, alexk2111 commented on StartAndroid/app/src/main/java/com/sigmasoftwere/akucherenko/startandroid/MainActivity.kt
> +    private val LOG_TAG = MainActivity::class.java.simpleName
Done

2021-09-20 11:52 UTC, alexk2111 commented on StartAndroid/app/src/main/java/com/sigmasoftwere/akucherenko/startandroid/MainActivity.kt
> +        mShowCount = findViewById(R.id.tv_show_count)
Done

2021-09-20 11:54 UTC, alexk2111 commented on StartAndroid/app/src/main/java/com/sigmasoftwere/akucherenko/startandroid/MainActivity.kt
> +        Toast.makeText(this, R.string.toast_message, Toast.LENGTH_SHORT).show()
Replaced Toast in clickListener

2021-09-20 11:54 UTC, alexk2111 commented on StartAndroid/app/src/main/java/com/sigmasoftwere/akucherenko/startandroid/MainActivity.kt
> +        if (mCount > 0)
Done

2021-09-20 11:55 UTC, alexk2111 commented on StartAndroid/app/src/main/res/layout-land/activity_main.xml
> +        android:id="@+id/tv_show_count"
All id's renamed

2021-09-20 11:56 UTC, alexk2111 commented on StartAndroid/app/src/main/res/layout-land/activity_main.xml
> +        android:background="#FFFF00"
Color moved to color.xml

2021-09-20 11:57 UTC, alexk2111 commented on TwoActivities/app/src/main/java/com/sigmasoftwere/akucherenko/twoactivities/MainActivity.kt
> +    private lateinit var mMessageEditText: EditText
Variables renamed

2021-09-20 11:57 UTC, alexk2111 commented on TwoActivities/app/src/main/java/com/sigmasoftwere/akucherenko/twoactivities/MainActivity.kt
> +class MainActivity : AppCompatActivity() {
line added

2021-09-20 11:58 UTC, alexk2111 commented on TwoActivities/app/src/main/java/com/sigmasoftwere/akucherenko/twoactivities/MainActivity.kt
> +
line removed

2021-09-20 11:58 UTC, alexk2111 commented on TwoActivities/app/src/main/java/com/sigmasoftwere/akucherenko/twoactivities/SecondActivity.kt
> +const val  EXTRA_REPLY = "com.sigmasoftwere.akucherenko.twoactivities.extra.REPLY"
Space removed

2021-09-20 11:59 UTC, alexk2111 commented on TwoActivities/app/src/main/java/com/sigmasoftwere/akucherenko/twoactivities/SecondActivity.kt
> +    private lateinit var mReply: EditText
Renamed

2021-09-20 12:00 UTC, alexk2111 commented on TwoActivities/app/src/main/java/com/sigmasoftwere/akucherenko/twoactivities/SecondActivity.kt
> +    override fun onCreate(savedInstanceState: Bundle?) {
Line added

2021-09-20 12:00 UTC, alexk2111 commented on TwoActivities/app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/editText_main"
Id's renamed

2021-09-20 12:04 UTC, alexk2111 commented on StartAndroid/.idea/.gitignore
> +# Default ignored files
Folder `.idea` added to `.gitignore`

2021-09-20 12:05 UTC, alexk2111 commented on TwoActivities/app/src/main/res/layout/activity_second.xml
> +        android:id="@+id/text_header"
Id's renamed

2021-09-20 18:17 UTC, merged